name: Sezione non aggiornata
description: Hai trovato informazioni obsolete che vanno aggiornate? Segnalalo qui.
title: "[AGGIORNAMENTO] "
labels: ["aggiornamento", "obsoleto"]
assignees:
  - Verryx-02
body:
  - type: markdown
    attributes:
      value: |
        Grazie per aver notato informazioni obsolete! La tecnologia cambia velocemente e il tuo aiuto è prezioso.
        
  - type: dropdown
    id: volume
    attributes:
      label: In quale volume hai trovato le informazioni obsolete?
      options:
        - Volume 1 (Consigli generali)
        - Volume 2 (Consigli per esami)
        - Volume 3 (Consigli fuori-sede)
        - README o file del repository
    validations:
      required: true
      
  - type: dropdown
    id: tipo_aggiornamento
    attributes:
      label: Che tipo di informazione va aggiornata?
      options:
        - Prezzi di PC/hardware
        - Software o applicazioni
        - Procedure universitarie (iscrizioni, tasse, ecc.)
        - Date o scadenze
        - Link o siti web
        - Informazioni sui corsi/esami
        - Informazioni sui luoghi in cui studiare
        - Altro
    validations:
      required: true
      
  - type: textarea
    id: posizione
    attributes:
      label: Dove si trova l'informazione obsoleta?
      description: Indica la sezione, pagina, o paragrafo
      placeholder: "Esempio: Volume 1, Capitolo 15.3, Pagina 13, Il GPT di Wolfram non sbaglia più"
    validations:
      required: true
      
  - type: textarea
    id: informazione_obsoleta
    attributes:
      label: Quale informazione è obsoleta?
      description: Copia il testo obsoleto o descrivi cosa non è più attuale
      placeholder: "Esempio:  Molto pi`u affidabile per calcoli e problemi matematici, perché utilizza l’API di WolframAlpha (anche se a volte sbaglia anche lui)"
    validations:
      required: true
      
  - type: textarea
    id: informazione_aggiornata
    attributes:
      label: Qual è l'informazione aggiornata?
      description: Fornisci l'informazione corrente se la conosci
      placeholder: "Esempio: Ormai il GPT di Wolfram non sbaglia più"
    validations:
      required: false
      
  - type: textarea
    id: fonte
    attributes:
      label: Fonte dell'aggiornamento (opzionale)
      description: Se hai una fonte affidabile, condividila
      placeholder: "Esempio: Siti ufficiali, comunicazione dell'università, ecc."
    validations:
      required: false
      
  - type: checkboxes
    id: conferma
    attributes:
      label: Conferma
      options:
        - label: Ho verificato che l'informazione sia effettivamente cambiata
          required: true
        - label: Ho letto le [linee guida per contribuire](https://github.com/Verryx-02/Scuola-di-sopravvivenza-per-studenti-di-Informatica/blob/main/CONTRIBUTING.md)
          required: true
